require 'mongoid/shell/properties/host'
require 'mongoid/shell/properties/primary'
require 'mongoid/shell/properties/database'
require 'mongoid/shell/properties/username'
require 'mongoid/shell/properties/password'
require 'mongoid/shell/properties/authentication_database'
require 'mongoid/shell/properties/ssl'
